[package]
name = "recall"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
regex = "1.0"
winapi = { version = "0.3.9", features = ["consoleapi", "wincon"] }
pest = "2.6"
pest_derive = "2.6"
rayon = "1.8"
itertools = "0.14"
rustc-hash = "2.1"